
FROM openjdk:17

WORKDIR /app

COPY build.gradle .
COPY src src
COPY gradle gradle

RUN ./gradlew build

COPY build/libs/demo-1.jar UdaApplication.jar

EXPOSE 9000

CMD ["java", "-jar", "UdaApplication.jar"]