
FROM openjdk:17-jdk-alpine

WORKDIR /app

COPY build.gradle .
COPY src src
COPY gradle gradle

RUN ./gradlew build

COPY build/libs/demo-1.jar ejercicio-saludo.jar

EXPOSE 9000

CMD ["java", "-jar", "ejercicio-saludo.jar"]